//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVentasDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria
    {
        public int cod_auditoria { get; set; }
        public string descripcion { get; set; }
        public int cod_usuario { get; set; }
        public System.DateTime fecha { get; set; }    
        public virtual Usuario Usuario { get; set; }
    }
}
