//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVentasDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria_Producto
    {
        public Categoria_Producto()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public int cod_cat_producto { get; set; }
        public string nombre_cat_producto { get; set; }
    
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
