//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVentasDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Negocio
    {
        public Negocio()
        {
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int cod_negocio { get; set; }
        public string nit_negocio { get; set; }
        public string nombre_negocio { get; set; }
        public string ciudad { get; set; }
        public string direccion { get; set; }
    
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
