//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVentasDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public Pedido()
        {
            this.PedidoProducto = new HashSet<PedidoProducto>();
        }
    
        public System.DateTime fecha { get; set; }
        public int cod_pedido { get; set; }
        public int cod_negocio { get; set; }
        public int cod_usuario { get; set; }
        public Nullable<int> total_pedido { get; set; }
        public string estado { get; set; }
    
        public virtual Negocio Negocio { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<PedidoProducto> PedidoProducto { get; set; }
    }
}
