//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVentasDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.PedidoProducto = new HashSet<PedidoProducto>();
        }
    
        public int cod_producto { get; set; }
        public string nombre_producto { get; set; }
        public int cantidad { get; set; }
        public int precio { get; set; }
        public string descripcion_producto { get; set; }
        public string ruta_foto { get; set; }
        public int cod_usuario { get; set; }
        public int cod_cat_producto { get; set; }
    
        public virtual Categoria_Producto Categoria_Producto { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<PedidoProducto> PedidoProducto { get; set; }
    }
}
