//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVentasUI.ServicioSincronizacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioSincronizacion.ISincronizacion")]
    public interface ISincronizacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISincronizacion/sincronizacionBajada", ReplyAction="http://tempuri.org/ISincronizacion/sincronizacionBajadaResponse")]
        string sincronizacionBajada(int codigoUltimoProducto, int codigoUltimoNegoci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISincronizacion/sincronizacionBajada", ReplyAction="http://tempuri.org/ISincronizacion/sincronizacionBajadaResponse")]
        System.Threading.Tasks.Task<string> sincronizacionBajadaAsync(int codigoUltimoProducto, int codigoUltimoNegoci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISincronizacion/sincronizacionSubida", ReplyAction="http://tempuri.org/ISincronizacion/sincronizacionSubidaResponse")]
        void sincronizacionSubida(string cadenaComprimidaSubida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISincronizacion/sincronizacionSubida", ReplyAction="http://tempuri.org/ISincronizacion/sincronizacionSubidaResponse")]
        System.Threading.Tasks.Task sincronizacionSubidaAsync(string cadenaComprimidaSubida);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISincronizacionChannel : SistemaVentasUI.ServicioSincronizacion.ISincronizacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SincronizacionClient : System.ServiceModel.ClientBase<SistemaVentasUI.ServicioSincronizacion.ISincronizacion>, SistemaVentasUI.ServicioSincronizacion.ISincronizacion {
        
        public SincronizacionClient() {
        }
        
        public SincronizacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SincronizacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SincronizacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SincronizacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string sincronizacionBajada(int codigoUltimoProducto, int codigoUltimoNegoci) {
            return base.Channel.sincronizacionBajada(codigoUltimoProducto, codigoUltimoNegoci);
        }
        
        public System.Threading.Tasks.Task<string> sincronizacionBajadaAsync(int codigoUltimoProducto, int codigoUltimoNegoci) {
            return base.Channel.sincronizacionBajadaAsync(codigoUltimoProducto, codigoUltimoNegoci);
        }
        
        public void sincronizacionSubida(string cadenaComprimidaSubida) {
            base.Channel.sincronizacionSubida(cadenaComprimidaSubida);
        }
        
        public System.Threading.Tasks.Task sincronizacionSubidaAsync(string cadenaComprimidaSubida) {
            return base.Channel.sincronizacionSubidaAsync(cadenaComprimidaSubida);
        }
    }
}
